name: sol-test-js
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.0.0
      - name: Run Mocha Chai Unit Test Action
        uses: EthereumRemix/ts-sol-test@main
        with:
          test-path: 'tests/test.ts'
          contract-path: 'contracts'
          compiler-version: '0.8.7'
